### ISSUE TITLE
Tulosta ilmoituksia-pluginista puuttuu navigointi

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-print-pdf-notices#1]
Pluginin yläreunasta puuttuu navigointi (breadcrumb), joten siitä ei pääse palaamaan Kohaan. Muissa plugineissa tällainen löytyy. Pieni vika, mutta käyttäjän kannalta ärsyttävä.

**Comment by AnneliO** [comment]
Muissa plugareissa lukee finglishiksi _Plugit_, sen voisi tähän laittaa suomeksi _Liitännäiset_. (Ja ehkä tehdä tiksu, että muissakin vaihdetaan termi suomenkieliseksi :D)

Raporttiplugari
![kuva](https://user-images.githubusercontent.com/33121325/232054755-d2cbb343-080e-4f29-9e97-2ab4c563de59.png)

Tarratulostusplugari
![kuva](https://user-images.githubusercontent.com/33121325/232054896-f5683504-3c67-45e9-9a50-3366fee2ad7f.png)

**Comment by emta001** [comment]
> Muissa plugareissa lukee finglishiksi _Plugit_, sen voisi tähän laittaa suomeksi _Liitännäiset_. (Ja ehkä tehdä tiksu, että muissakin vaihdetaan termi suomenkieliseksi :D)
> 
> Raporttiplugari ![kuva](https://user-images.githubusercontent.com/33121325/232054755-d2cbb343-080e-4f29-9e97-2ab4c563de59.png)
> 
> Tarratulostusplugari ![kuva](https://user-images.githubusercontent.com/33121325/232054896-f5683504-3c67-45e9-9a50-3366fee2ad7f.png)

Nämäkin pitäis nyt olla korjatut, vaikka eivät vielä nexteillä näykään :)
