### ISSUE TITLE
Kotikirjastolla suodattamisen korvaaminen sähköpostilla suodattamisella

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-print-pdf-notices#2]
Siilin kanssa törmättiin ongelmaan noreply-osoiteiden ja PDF-viestien haun kanssa. Yhteisössä on muutettu tapaa jolla varausten saapumisilmoituksiin määritetään message_queue.from_address arvo. Aiemmin arvona on käytetty kirjaston sähköpostia, mutta uudessa versiossa käytetäänkin vastausosoitetta. Siilissä pääkirjaston ja kirjastoauton sähköpostina käytetään [noreply@koha-suomi.fi](mailto:noreply@koha-suomi.fi) osoitetta, kun taas vastausosoitteena on [kirjasto@siilinjarvi.fi](mailto:kirjasto@siilinjarvi.fi). Mutta plugin rajaa viestit kirjaston sähköpostin perusteella, Siilin pääkirjaston ja kirjastoauton tapauksessa siis noreply-osoitteella.

Ongelma korjattiin Siilissä ottamalla vastausosoitteet pois käytöstä, mutta tämä ei tule onnistumaan Kyytissä.

Ratkaisuksi hahmoteltiin seuraavaa:
1. Otetaan pois API-kutsusta from_address-kentällä rajaus.
2. Korjataan olemassa oleva suodatus suodattamaan sähköposti-osoitteen perusteella (pitää vain ensin tarkistaa mitä spostia käytetään).

**Comment by emta001** [comment]
Lisään tämän Versionvaihto-projektiin, korjaillaan versionvaihdon yhteydessä tämä.

**Comment by emta001** [comment]
Testeille on nyt viety korjaus tuohon kohtaan 1. Viestejä haettassa kaikkien viestien, joiden toimitustapa on print ja jotka ovat tyypiltään joko "HOLD", "ODUE1" tai "ODUE2" sekä ovat pending tilassa, tulisi nyt näkyä listalla riippumatta niiden lähetysosoitteesta.

**Comment by ReettaSiili** [comment]
Testasin Siilin testillä: lisäsin kaikkien kolmen kirjaston tietoihin vastausosoitteen kirjasto@siilinjarvi.fi ja asetukseen ReplytoDefault myös saman osoitteen. Tein varaukset kaikkiin kirjastoihin ja kaikki kolme saapumisilmoitusta tulivat näkyviin Tulosta ilmoituksia -työkaluun. Toimii!

**Comment by Tuomas-Kyyti** [comment]
Viime viikon sähköpostiosoitemuutosten myötä tämä työkalu ei enää toimi oikein Kyytissä. Miten tämä saadaan Kyytin osalta kuntoon? 

Tämän hetken tilanne:
- kirjastoasetuksissa: sähköposti-kentässä: noreply@koha-suomi.fi ja vastausosoitteena kirjastopisteen oma osoite
- työkalussa näkyy kaikkien kirjastojen odottavat viestit riippumatta kirjautumiskirjastosta
- suodatus tapahtuu kirjastopiste-sarakkeen mukaan, mutta siinä oleva tieto on asiakkaan kotikirjasto, joka ei tässä kohtaa auta yhtään, koska noutokirjasto, jonka viesti pitäisi tulostaa, voi olla eri.
- työkalun sähköposti-sarake on tyhjä
- työkalun kirjaston sähköposti -sarakkeessa on noreply@koha-suomi.fi

Tällä hetkellä työkalusta ei siis näe mitkä viestit kirjaston pitäisi tulostaa.

**Comment by ReettaSiili** [comment]
Tarkennus Siilistä: en ollut hoksannut testata tuota suodatusta ollenkaan, koska meillä sitä ei tarvita, kaikki kirjeet tulostetaan ja postitetaan pääkirjastossa. Pahoittelut.

Kun nyt testasin suodatusta, se ei Siili-testillä toimi, tai siis toimii juuri niinkuin Tuomas yllä kertoo: suodatus tapahtuu asiakkaan kotikirjaston mukaan, ei varauksen noutopaikan mukaan.

**Comment by emta001** [comment]
Ongelmana tässä on nyt se, että meillä ei ole mitään muuta keinoa rajata viestejä kuin asiakkaan kotikirjastolla. Viestitaulusta ei kyetä poimimaan tietoa siitä, missä kirjastossa varaukset on tehty, eikä sitä missä kirjastossa viesti on generoitu. Yhteisössä on lisätty tauluun reply_address-sarake, johon pitäisi täydentyä ilmeisesti kirjaston sähköpostiosoite, mutta sitä ei käytetä mihinkään eikä siihen täydenny mitään. Joten ainoaksi keinoksi jää tuo asiakkaan kotikirjastolla suodattaminen.

**Comment by Tuomas-Kyyti** [comment]
Pärjäämme tällä, kun hiukan hiomme käytäntöjämme.

**Comment by emta001** [comment]
Tämän voinee sulkea.
